solace-db:
  bindings:
    input-0:
      consumer:
        format: json   #json or xml
        tableKey: test_identification
        tableClass: com.solace.connectors.database.source.entity.TestIdentification
        #childTableKey: passAddress
        #childTableClass: com.solacecoe.connectors.database.source.entity.PassAddress
        topic: db/oracle/test_identification
        lvqTopic: lvq/pmacs
        #parentChildRelationKey: passengerId:passId   #,address:city
        #dbParentChildMode: one2many #many2one
        #dbParentCollection: addresses
        #dbChildTable: passAddress
        #dbReadIndicatorColumn: flag
        #dbTrackingId: id
        #dbReadTime: readtime
        dbReadRecordSequentialIndicator: id
        dbReadRecordSequentialOrder: asc
        dbReadIndicatorBridgeFailedValue: true
        dbReadIndicatorBridgeInProgressValue: true
        #              enableMessageHeaderTrackId: true
        #              messageHeaderTrackId: dbTrackId
        #propertiesEnabled:
        #  dbTrackingId: false
        #  dbReadTime: false
        #customMessageHeaders:
          #TRACK_ID: id
    input-1:
      consumer:
        tableKey: source_passenger1
        tableClass: com.solacecoe.connectors.database.source.entity.SourcePassenger1
        childTableKey: passAddress1
        childTableClass: com.solacecoe.connectors.database.source.entity.PassAddress1
        topic: data/pmacs1/{COL:passengerId}
        lvqTopic: lvq/pmacs1
        parentChildRelationKey: passengerId:passId   #,address:city
        dbParentChildMode: one2many #many2one
        dbParentCollection: addresses
        dbChildTable: passAddress
        dbReadIndicatorColumn: flag
        dbTrackingId: dbtrackid
        dbReadTime: readtime
        dbReadIndicatorColumnUpdateValueInProgress: p
        dbReadIndicatorColumnUpdateValueProcessed: c
        dbReadIndicatorColumnUpdateDefaultValue: n
        dbReadIndicatorColumnUpdateFailedValue: f
        #dbReadRecordSequentialIndicator: id.passengerId
        dbReadRecordTimestampIndicator: id.createdAt
        dbReadRecordSequentialOrder: asc
        dbReadIndicatorBridgeFailedValue: true
        dbReadIndicatorBridgeInProgressValue: true
        #              enableMessageHeaderTrackId: true
        #              messageHeaderTrackId: dbTrackId
        propertiesEnabled:
          dbTrackingId: true
          dbReadTime: true
        customMessageHeaders:
          TRACK_ID: dbtrackid