solace-connector-mapper:
  mapper-metadata:
    escape-special-characters: true
    schema-type:
    encrypted:
  payload-mapper:
    mapper-name0:
      source-xpath: test_identification/id
      source-datatype:
      target-xpath: passenger/id
      target-datatype:
    mapper-name1:
      source-xpath: test_identification/testName
      source-datatype:
      target-xpath: passenger/pname
      target-datatype:
    mapper-name2:
      source-xpath: test_identification/createdAt
      source-datatype:
      target-xpath: passenger/birthday
      target-datatype: